### PR TITLE
Rename a few auth headers and add some more

### PR DESCRIPTION
**Pull request by jszanto**
This is something the CBC would like to use for future authentication integrations

### CODE REVIEW

**Comment by Koen1999** [comment]
I'm not completely familiar with the way these headers work, but I'd like some clarification.
Aren't headers visible to anyone sniffing around on the network?

**Comment by wsinnema** [comment]
The routes that have the headers will be blocked by the reverse proxy. It is
therefore only visible for other webapps running on the same server, and the
reverse proxy itself.

**Comment by Koen1999** [comment]
Alright, good to know. Then we can merge this PR once it is tested and the reverse proxy is properly configured.

**Comment by jszanto** [comment]
The headers are only visible if you are logged in, so if these routes are exposed (which they currently are) then you can only see the headers for yourself. And for people sniffing around on the network, TLS prevents that.

This also has been tested already btw.

**Pull request merged**
