### PR TITLE
Added years to album breadcrumbs.

### LINKED ISSUE #578: Add years to photo breadcrumbs

### PR DESCRIPTION
**Pull request by gafderks**
Fixes #578

### CODE REVIEW

**Comment by stefanmajoor** [comment]
@jszanto Since this code is already duplicated, both in my PR as here, maybe it is time to create a library or something for this. E.g. just a app that regulates everything w.r.t. study years. Especially since this may be needed in the future too.

**Comment by jszanto** [comment]
@stefanmajoor Good idea, perhaps something like this?

```
class AssociationYear {

	public static function fromYear($year); // Returns instance of AssociationYear
	public static function fromDate($dateTime); // Returns instance of AssociationYear

	public function getYear(); // Returns 2015
	public function getYearString(); // Returns 2015-2016
	public function getStartDate(); // Returns DateTime('1-7-2016)
	public function getEndDate(); // Returns DateTime('30-6-2016)

}
```

**Comment by gafderks** [comment]
@jszanto Where would I locate such a class? As a service in the Decision module?

**Comment by jszanto** [comment]
@gafderks I think a model that isn't persisted in the database would be the best option. Since it doesn't really expose any services.

**Pull request merged**
