### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by Koen1999**

### CODE REVIEW

**Comment by Koen1999** [comment]
The issue detected by Psalm is a non-issue, so I added it to the baseline for future PRs.

**Comment by tomudding** [comment]
Can you rebase and redo the baseline update? Also, it would be nice if you could name the branch something like `dependencies/2023-01` (or along those lines), that makes it easier to checkout the branch on my end.

**Comment by Koen1999** [comment]
I'll keep the branch naming in mind for you next time @tomudding .

I've updated the PR by rebasing onto master.
Please see the psalm report:
```
[koen@fedora gewisweb]$ make psalm
Warning: "findUnusedBaselineEntry" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Target PHP version: 8.2 (inferred from current PHP version) Enabled extensions: dom, pdo (unsupported extensions: fileinfo, imagick, memcached, pdo_pgsql, zend-opcache).
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  60 / 375 (16%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 120 / 375 (32%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 180 / 375 (48%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 240 / 375 (64%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 300 / 375 (80%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 360 / 375 (96%)
░░░░░░░░░░░░░░░

------------------------------
                              
       No errors found!       
                              
------------------------------
69 other issues found.
You can display them with --show-info=true
------------------------------
Psalm can automatically fix 5 of these issues.
Run Psalm again with 
--alter --issues=InvalidNullableReturnType,InvalidReturnType --dry-run
to see what it can fix.
------------------------------

Checks took 21.25 seconds and used 825.573MB of memory
Psalm was able to infer types for 90.4022% of the codebase
```

**Review by tomudding — APPROVED** [review]
LGTM!

**Pull request merged**
