### PR TITLE
Created production image for docker to be deployed with Portainer

### PR DESCRIPTION
**Pull request by Koen1999**
Still WIP

### CODE REVIEW

**Comment by Koen1999** [comment]
A current blocking issue is that the environment variables are substituted into the config file (config/autoload/doctrine.local.php) at build time instead of at the time of deployment. I am not sure how to fix this.

**Comment by Koen1999** [comment]
TODO, take #1064 into account

**Comment by Koen1999** [comment]
@kokx @Kevinjil 
Does one of you know why we make use of docker to install php extensions while we also make use of composer to manage these including the versions?
I have been thinking about this and I think it makes more sense to stick with only composer.

**Comment by tomudding** [comment]
> Does one of you know why we make use of docker to install php extensions while we also make use of composer to manage these including the versions?

@Koen1999 Packagist does not have all (or any) of the PHP extensions. It does have [platform packages](https://getcomposer.org/doc/01-basic-usage.md#platform-packages) for the extension. These are used to compare versions, however, this can be very inconsistent. This is the reason we have the following two lines in `composer.json`:

    "ext-gd": "^0.0.0",
    "ext-exif": "^0.0.0",

We cannot install them via Composer, but we can make sure they are present.

**Pull request merged**
