### PR TITLE
Design update education page

### PR DESCRIPTION
**Pull request by armandduijn**
**Before**:
download

**After**:
download 1

download 3

### CODE REVIEW

**Comment by armandduijn** [comment]
**Note**: This PR is based on the code from PR #623.

**Comment by armandduijn** [comment]
Yay or nay? @kokx @jszanto 

schermafbeelding 2017-07-15 om 17 13 52

**Comment by kokx** [comment]
Ik zou ipv die yTU/e button, daar een eigen pagina met verzamelde links van maken.

**Comment by armandduijn** [comment]
What a strange combination of letters @kokx and @Mesoptier are using. Some alien language I'm unfamiliar with.

@Mesoptier The class has been added. This makes them more visible, indeed.

@kokx I'm not sure if creating a separate page with useful links is the right direction. Why reinvent the wheel if yTU/e has a fine repository of links? Is there maybe a reason why we don't want to affiliate ourselves with this website?

**Comment by armandduijn** [comment]
Resolves #670

**Comment by armandduijn** [comment]
@jszanto Rebased on #623 and fixed merge conflicts in translation files. Even translated some untranslated strings. Code Climate fails are due to the some JavaScript related to the style guide. Out of the scope of this PR. 

Good to merge.

**Pull request merged**
