### PR TITLE
Alter design of gewis.nl/photo

### PR DESCRIPTION
**Pull request by Staartvin**
See BIG SCREENimage

And

SMALL SCREEN
image

### CODE REVIEW

**Comment by jszanto** [comment]
Perhaps we could use this same album style for subalbums too?

**Comment by armandduijn** [comment]
I like the new design! However, it's not immediately clear what the dates under each album name mean. The creation date? Or the last modified date?

**Comment by jszanto** [comment]
The dates are the date when the foto's were taken.

**Comment by jszanto** [comment]
And two small issues at different screen sizes:
screen shot 2017-12-10 at 17 32 34
and:
screen shot 2017-12-10 at 17 33 07

**Comment by Mesoptier** [comment]
I like the design. The code for the styles (classnames for example) needs to be improved before merging. I can look at that next week.

**Comment by Staartvin** [comment]
@jszanto The first issue is fixed, but the second one is little harder. It occurs when titles are too long, right?

**Comment by jszanto** [comment]
@Staartvin Yes, it occurs (on medium sized screens) when the titles don't fit on one line anymore. I suppose it could be fixed by setting a min-height for the header, but that might be ugly.

**Comment by jszanto** [comment]
@Mesoptier @Staartvin Any updates on this?

**Comment by Staartvin** [comment]
@jszanto I've fixed the first issue, but could not resolve the second issue. Perhaps @Mesoptier could look into this?

**Comment by Kevinjil** [comment]
Something like [this](https://gist.github.com/Kevinjil/042214dd617c6190fbdc3e0803b743ac) could be used to fix the column alignment with long titles. It would most likely be a good idea to modify that to create less general selectors.

**Comment by StephanvandenBerkmortel** [comment]
This is a problem with the current photo page design as well. For that design I posed a solution <a href="https://github.com/GEWIS/gewisweb/pull/819">here</a> and can probably be applied to the new design as well.

**Pull request closed without merging**
