### PR TITLE
Feature/activity calendar

### PR DESCRIPTION
**Pull request by armandduijn**
screenshot
screenshot 1

### CODE REVIEW

**Comment by armandduijn** [comment]
I noticed that "De website slopen optie 2" was supposedly deleted by me but I didn't delete it. Is the user id recorded correctly?

**Comment by jszanto** [comment]
Seems to be caused by this line https://github.com/GEWIS/gewisweb/pull/624/commits/994afd333e7452d0f4466be753a609a8d6f3d3cc#diff-34af195c4974dfb86d94aa341dec4d0aR134 it should be `getDeletedBy` instead of `getCreator`

**Comment by armandduijn** [comment]
@gafderks @Mesoptier If someone has time, could you clean up the CSS? It's all inline right now and it isn't SASS.

**Comment by gafderks** [comment]
@armandduijn Next Friday, I can take a look at it.

**Comment by gafderks** [comment]
@armandduijn I've fixed the styling.

**Comment by jszanto** [comment]
Thanks @gafderks! So then I can merge this now @armandduijn?

**Comment by armandduijn** [comment]
Good fixes by @gafderks. Are we going to fix the codeclimate issues? If not, merge away!

**Comment by jszanto** [comment]
The remaining code climate issues aren't really fixable, so we can leave them for now.

**Comment by armandduijn** [comment]
Ok. Then you can merge it.

**Pull request merged**
