### PR TITLE
Fixed dropdown buttons in the main navigation.

### LINKED ISSUE #736: Improvement dropdowns main navigation
The dropdowns can be improved such that no refresh of the page is required for opening them on a mobile phone.

### PR DESCRIPTION
**Pull request by gafderks**
Fixes #736

### CODE REVIEW

**Comment by gafderks** [comment]
@Mesoptier Can you verify whether this PR conflicts with your redesign of the front page?

**Comment by gafderks** [comment]
@Mesoptier the problem is that we do want the dropdowns to open on hover when the screen is large while we want the dropdowns to open on click on mobile devices. This is not functionality that is in the default navbar. Unfortunately, the solution is not straightforward since the buttons themselves also need to link to a new page on large screens, while on mobile screens this behavior prevents the user from opening the dropdown.

**Comment by Mesoptier** [comment]
@gafderks Ah, that makes sense. Well in that case this PR is fine by me.

**Comment by armandduijn** [comment]
Hmm it's lacking in usability. I would prefer if there was pointy arrow (▼) to communicate that a menu item is a dropdown. It should also point upwards (▲) when the dropdown is expanded.

**Comment by gafderks** [comment]
@armandduijn I've implemented this feature.

**Pull request merged**
