### PR TITLE
Updated the glide image to PHP 8.0

### PR DESCRIPTION
**Pull request by Koen1999**
and updated other dependencies

Having to build images for multiple PHP versions is bad for my cache

### CODE REVIEW

**Review by tomudding — CHANGES_REQUESTED** [review]
Can you also update the PHP version in glide's composer.json?

As long as  don't share the same machine when building the images (we really need a pipeline) we will have bad caching of the layers.

**Comment by Koen1999** [comment]
> 
> 
> Can you also update the PHP version in glide's composer.json?
> 
> Side note:
> As long as don't share the same machine when building the images (we really need a pipeline) we will have bad caching of the layers.

Well, the image also works with PHP 5.6. So we don't need to bump the requirement in my opinion.

**Comment by tomudding** [comment]
> > Can you also update the PHP version in glide's composer.json?
> > Side note:
> > As long as don't share the same machine when building the images (we really need a pipeline) we will have bad caching of the layers.
> 
> Well, the image also works with PHP 5.6. So we don't need to bump the requirement in my opinion.

`league/flysystem` (and some other packages) requires at least PHP 7.2(.5), so we should bump it to that in my opinion.

**Comment by Koen1999** [comment]
> 
> 
> > > Can you also update the PHP version in glide's composer.json?
> > > Side note:
> > > As long as don't share the same machine when building the images (we really need a pipeline) we will have bad caching of the layers.
> > 
> > 
> > Well, the image also works with PHP 5.6. So we don't need to bump the requirement in my opinion.
> 
> `league/flysystem` (and some other packages) requires at least PHP 7.2(.5), so we should bump it to that in my opinion.

But since this dependency is in composer.json, we will require it transitively. And if dependencies are installed using the lock file, this will be required for sure.

**Comment by tomudding** [comment]
> 
> 
> > > > Can you also update the PHP version in glide's composer.json?
> > > > Side note:
> > > > As long as don't share the same machine when building the images (we really need a pipeline) we will have bad caching of the layers.
> > > 
> > > 
> > > Well, the image also works with PHP 5.6. So we don't need to bump the requirement in my opinion.
> > 
> > 
> > `league/flysystem` (and some other packages) requires at least PHP 7.2(.5), so we should bump it to that in my opinion.
> 
> But since this dependency is in composer.json, we will require it transitively. And if dependencies are installed using the lock file, this will be required for sure.

I am only asking because you asked the same for the main composer.json when I updated the main containers to PHP 8.0 (we now have PHP 8.0 specific functions, but back then we still supported 7.4). Some consistency is needed in my opinion.

I will test this thoroughly tomorrow before approving.

**Review by tomudding — APPROVED** [review]

**Pull request merged**
