### PR TITLE
Highlighted how to become a member

### PR DESCRIPTION
**Pull request by Koen1999**
This solves #1209

### CODE REVIEW

**Comment by Koen1999** [comment]
Please note that I opted for a shorter text as described in the issue because it would disturb the navbar too much on mobile devices.
afbeelding
afbeelding

**Comment by Koen1999** [comment]
I am also adjusting the registration page to look like this
afbeelding

**Comment by rinkp** [comment]
Perhaps you can call the current registration the "activation" of one's account? That makes it distinct from registering for GEWIS

**Comment by Koen1999** [comment]
> 
> 
> Perhaps you can call the current registration the "activation" of one's account? That makes it distinct from registering for GEWIS

I think we currently have the idea of registering an account and subscribing to become a member. So they are distinct, but it's a bit vague, I agree.

**Comment by Koen1999** [comment]
Also, the first commit in this PR is to make pages like https://gewis.nl/vereniging/exceptionalmembers work with content from subdomains. Not really related, but I guess we need to process this change some time.

**Review by LeonVreling — APPROVED** [review]
Looks good

**Comment by LeonVreling** [comment]
Will the board need to make the page with benefits of becoming a member, the one referenced at gewis.nl/vereniging/lidworden (or what the English URL turned out to be)

**Comment by Koen1999** [comment]
> 
> 
> I think that the board still needs to make the page with the benefits of becoming a member to make it fully functional, the one referenced at [gewis.nl/vereniging/lidworden](https://gewis.nl/vereniging/lidworden) (or what the English URL turned out to be)

Yep, that's what I am currently waiting for. I will merge and deploy once that page is created in case I need to adjust the URL in the code.

**Review by tomudding — COMMENTED** [review]
> 
> 
> afbeelding

I do not agree with this change, the navbar now takes up 1/3rd of your screen. On every single page. This affects many modern phones, as the viewport is commonly 360 pixels (it does not fit) to 412 pixels (it barely fits), see [Common Viewport Sizes](https://yesviz.com/viewport/).

Furthermore, if we have to keep adding and removing this link each year, just make it hide itself based on some date range (this can be done later).

**Comment by tomudding** [comment]
I recommend we more or less go back to what we had in the past. A submenu, however, with just two links. One to the login page, and one to the new `lidworden` page. _Sidenote_, why isn't there a `-` between `lid` and `worden`? It makes the URL look a lot better.

This is what it looks like on a phone:
GEWIS-WEB #1212 Improved Menubar Becoming A Member Collapsed - cropped
GEWIS-WEB #1212 Improved Menubar Becoming A Member Extended - Cropped

And for desktop users:
image

**Comment by Koen1999** [comment]
@tomudding The changes you made look good!

**Pull request merged**
