### PR TITLE
Fix unintended, annoying and unnecessary feature

### LINKED ISSUE #682: Use a queue for mail
Currently most emails are sent inside the request which is not a good idea. It leads to reduced performance and mail errors result in the request failing.

### PR DESCRIPTION
**Pull request by armandduijn**
Fixes #682 #723 #733.

**Impact**: Improves the mood of the developers and saves costly bandwidth and storage.

### CODE REVIEW

**Comment by armandduijn** [comment]
What needs to be checked? Is it something we can do automatically?

**Comment by jszanto** [comment]
The changes need to be reviewed before they are placed on the website. This is why you receive an email prompting you to review them. Perhaps fixing this is a better idea: https://github.com/GEWIS/gewisweb/issues/723

**Comment by jszanto** [comment]
Also disabling the emails whenever an admin does something would already reduce the amount by 50%

**Comment by armandduijn** [comment]
In light of new information, this PR has been deemed unnecessary.

**Pull request closed without merging**
