### PR TITLE
Organ mutations

### PR DESCRIPTION
**Pull request by kokx**

### CODE REVIEW

**Comment by stefanmajoor** [comment]
As I understand correctly, the data is fully truncated during the progress of this script, and the data is not available at the GEWIS website. Since the data is read only anyway, and this procedure does not allow this data to be refered to (since foreign keys might be violated), why not do it in a transaction?

**Comment by kokx** [comment]
@stefanmajoor It is now using transactions.

**Comment by kokx** [comment]
@jszanto @stefanmajoor Can this be merged, or are there things that prevent that?

**Comment by jszanto** [comment]
If @stefanmajoor has no further concerns, then this can be merged.

**Pull request merged**
