### PR TITLE
Fix typing for all modules

### LINKED ISSUE #1126: PHP 7.4: Add type hints to functions and properties
This is a newly supported feature but also affects the behaviour of the runtime execution.

I propose first improving the PhpDoc for all functions and reviewing the stability with PhpStan.
After that we can automatically generate the type hints with the PHP Code Beautifier.

Would require serious testing.

### PR DESCRIPTION
**Pull request by tomudding**
This PR is based on #1309 and should be rebased once that is merged. Fixes (almost) all typing issues which are currently present in the code.

To accomplish this, I have locally changed my PHPStan configuration to be like this:

```yml
level: 6
treatPhpDocTypesAsCertain: true
checkMissingIterableValueType: false
checkGenericClassInNonGenericObjectType: false
```

The last two are necessary at the moment, because I do not have the time and motivation to determine all correct types for `arrays`, `Collection`s, etc.

**Modules:**
- [X] Activity
- [x] Application
- [x] Company
- [x] Decision
- [x] Education
- [x] Frontpage
- [x] Photo
- [x] User

This closes #1126.

### CODE REVIEW

**Comment by Koen1999** [comment]
I think the order could better be not alphabetic due to inter-module dependencies. Try doing the User and Decision module next and the Frontpage last.

`Fatal error: Declaration of User\Authorization\GenericAclService::getRole() must be compatible with Application\Service\AbstractAclService::getRole(): Laminas\Permissions\Acl\Role\RoleInterface|string in /code/module/User/src/Authorization/GenericAclService.php on line 42`

**Comment by tomudding** [comment]
> I think the order could better be not alphabetic due to inter-module dependencies. Try doing the User module next.
> 
> `Fatal error: Declaration of User\Authorization\GenericAclService::getRole() must be compatible with Application\Service\AbstractAclService::getRole(): Laminas\Permissions\Acl\Role\RoleInterface|string in /code/module/User/src/Authorization/GenericAclService.php on line 42`

This exposes my development strategy a bit. I can only do this because we (at the moment) cannot use `git bisect`. I push per module, but locally I have the changes from all other parts that are broken.

When I pushed the updates for these three branches everything was already fixed locally but not on the remote. Regarding the order, a bit too late because I already have finished all modules in alphabetical order (I just need to push them).

I do intend to squash the 8 commits unless you prefer I keep it this way.

**Comment by Koen1999** [comment]
> > I think the order could better be not alphabetic due to inter-module dependencies. Try doing the User module next.
> > `Fatal error: Declaration of User\Authorization\GenericAclService::getRole() must be compatible with Application\Service\AbstractAclService::getRole(): Laminas\Permissions\Acl\Role\RoleInterface|string in /code/module/User/src/Authorization/GenericAclService.php on line 42`
> 
> This exposes my development strategy a bit. I can only do this because we (at the moment) cannot use `git bisect`. I push per module, but locally I have the changes from all other parts that are broken.
> 
> When I pushed the updates for these three branches everything was already fixed locally but not on the remote. Regarding the order, a bit too late because I already have finished all modules in alphabetical order (I just need to push them).
> 
> I do intend to squash the 8 commits unless you prefer I keep it this way.

You can squash since the codebase is not very functional inbetween commits.

**Comment by Koen1999** [comment]
I suggest you rebase this on master so we can see the GitHub actions in action

**Comment by tomudding** [comment]
> I suggest you rebase this on master so we can see the GitHub actions in action

Yes, I messed up the squash it is taking a bit longer than expected.

**Comment by tomudding** [comment]
@Koen1999 The results are available, it would have been nice if we actually had unit tests for everything. It does unfortunately appear that the PHPStan action is borked.

**Comment by Koen1999** [comment]
I fixed it on master branch @tomudding

**Review by Koen1999 — APPROVED** [review]

**Comment by tomudding** [comment]
Please do not merge just yet. While I am pretty sure there aren't any more bugs then there were previously in master (probably a bit less even) I do need at least one more day to check it.

**Comment by Koen1999** [comment]
Since you also fixed the level 6 issues, I suggest raising the Phpstan level in the config as well.

**Comment by tomudding** [comment]
I'll be merging this in a bit as I do not see any issues related to the typing changes we have implemented.

**Pull request merged**
