### PR TITLE
Updated subscription form layout for activity subscription.

### LINKED ISSUE #745: Improve alignment of extra fields on activities
These errors occur:
image

### PR DESCRIPTION
**Pull request by gafderks**
Fixes #745

### CODE REVIEW

**Comment by gafderks** [comment]
image
The subscribe now button opens and collapses the subscription form. Initially it is closed.

**Comment by jszanto** [comment]
@armandduijn Can you check this out?

**Comment by gafderks** [comment]
Resolved merge conflicts.

**Comment by armandduijn** [comment]
I have a few remarks:

- [Add spacing between button title](https://user-images.githubusercontent.com/706385/34908507-fc823970-f890-11e7-9969-f86319c8d33a.png)
- [Prevent double confirmation if the activity doesn't require extra info](https://user-images.githubusercontent.com/706385/34908519-35b3012a-f891-11e7-9b3d-8d4cc518782b.png)

Other remarks that are just a matter of taste (non-blocking):

- [Limit input width on larger screens](https://user-images.githubusercontent.com/706385/34908567-08baffc8-f892-11e7-9139-a627dea4c40d.png)
- Have the caret icon rotate 90 degrees clockwise when the panel is open

**Comment by gafderks** [comment]
@armandduijn I have addressed the issues that you have mentioned. Note that you need to recompile the CSS for the spacing to be correct.

**Comment by gafderks** [comment]
@armandduijn Can you review this pull request?

**Comment by gafderks** [comment]
Resolved merge conflict.

**Comment by Kevinjil** [comment]
Merged into [testing](https://github.com/GEWIS/gewisweb/tree/testing) and noticed that the panel can still be opened when the subscription deadline is closed (even though it is empty). Maybe add a disabled flag to the button or something like that?
image

**Comment by gafderks** [comment]
@Kevinjil I have resolved this issue as well as the issue with the margin between the list of subscribed members and the subscription button.

**Pull request merged**
