### PR TITLE
Revert "Removed some code artefact from a board gift"

### PR DESCRIPTION
**Pull request by kokx**
This reverts commit 3211a3fa3d55a563bae6cf882a60a4f74e18c2b4.

Super important fix. Pls merge ASAP.

### CODE REVIEW

**Review by Kevinjil — APPROVED** [review]

**Review by tomudding — APPROVED** [review]

**Review by Koen1999 — CHANGES_REQUESTED** [review]
I seriously doubt whether we want to keep this in our codebase. They have enjoyed it for long enough.

**Comment by LeonVreling** [comment]
I think it would be nice to keep, but that might just be a biased opinion

**Comment by kokx** [comment]
Might be nice for the current board as well.

**Comment by Koen1999** [comment]
If we want to keep this, sure. But then we should refactor the code a bit. The way I introduced it in the past was not meant to be maintained.

**Comment by tomudding** [comment]
I am closing this pending another PR which will implement this in a better way (using the new `isBoardMember` functions).

**Pull request closed without merging**
