### PR TITLE
Create .codeclimate.yml

### PR DESCRIPTION
**Pull request by efueger**
Add .codeclimate.yml, disable CSSLint

### CODE REVIEW

**Comment by kokx** [comment]
Wow. Apparently there exist bots now that automatically create pull requests to push certain config files.

**Comment by jszanto** [comment]
Actually not a a bot

**Comment by stefanmajoor** [comment]
Why is this merged? Are we actually going to use codeclimate? If not, I think this should be reverted

**Comment by jszanto** [comment]
I am currently testing it, it may be useful to help review PRs. For example code climate easily finds stuff like formatting issues, logic errors, unclear code, debug code, etc. This would save a dozen comments everytime we review a PR.

**Pull request merged**
