### PR TITLE
Fix PHPStan issues

### PR DESCRIPTION
**Pull request by tomudding**
To enable #1308 (if chosen) to work or as a general improvement, this fixes most of the current PHPStan issues present on master.

There are some remaining issues, of which most should be ignored in the baseline:

1) There is currently no functionality to better type these values in `laminas/form`.
```php
 ------ ------------------------------------------------------------------------------
  Line   module/Activity/src/Controller/AdminOptionController.php
 ------ ------------------------------------------------------------------------------
  92     Call to an undefined method Laminas\Form\ElementInterface::setCount().
  102    Call to an undefined method Laminas\Form\ElementInterface::count().
  103    Call to an undefined method Laminas\Form\ElementInterface::setCount().
  114    Call to an undefined method Laminas\Form\ElementInterface::populateValues().
  165    Call to an undefined method Laminas\Form\ElementInterface::setCount().
  185    Call to an undefined method Laminas\Form\ElementInterface::setCount().
 ------ ------------------------------------------------------------------------------
```

2) There is currently no functionality to better type these values in `laminas/form`.
```php
 ------ -------------------------------------------------------------------------------
  Line   module/Activity/src/Form/Activity.php
 ------ -------------------------------------------------------------------------------
  201    Call to an undefined method Laminas\Form\ElementInterface::getValueOptions().
  206    Call to an undefined method Laminas\Form\ElementInterface::setValueOptions().
  208    Call to an undefined method Laminas\Form\ElementInterface::getValueOptions().
  213    Call to an undefined method Laminas\Form\ElementInterface::setValueOptions().
  220    Call to an undefined method Laminas\Form\ElementInterface::setValueOptions().
  282    Call to an undefined method Laminas\Form\ElementInterface::getFieldSets().
 ------ -------------------------------------------------------------------------------
```

3) `unwrap()` is part of `PersistentCollection`. We could change the type (for all `(Array)Collections`) to `Collection|PersistentCollection`, just `PersistentCollection` does not work as we have to initialise the attributes when creating the entities (before persisting them).
```php
 ------ -------------------------------------------------------------------------------
  Line   module/Activity/src/Service/Activity.php
 ------ -------------------------------------------------------------------------------
  461    Call to an undefined method Doctrine\Common\Collections\Collection::unwrap().
 ------ -------------------------------------------------------------------------------
```

4) There is currently no functionality to better type these values in `laminas/form`.
```php
 ------ -------------------------------------------------------------------------------
  Line   module/Decision/src/Form/Notes.php
 ------ -------------------------------------------------------------------------------
  80     Call to an undefined method Laminas\Form\ElementInterface::setValueOptions().
 ------ -------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by tomudding** [comment]
Quick note, this is of course level 5 of PHPStan. If I have the motivation I'll do level 6 too.

**Comment by Koen1999** [comment]
Level 6 requires a lot of typing which it was not added so far.

**Comment by tomudding** [comment]
> Level 6 requires a lot of typing which it was not added so far.

I won't commit the actual change level change, but a lot of issues (return types) can already be fixed. I won't be fixing the controller action return types and the "no value type specified in iterable type" (which occurs like 500 times) though.

**Review by Koen1999 — APPROVED** [review]
Looks good!

**Comment by Koen1999** [comment]
While I approve of the changes made in this PR, there's still some issues remaining.

```
koen@koen-HP-ZBook-Studio-G4-Kubuntu:~/gewisweb/gewisweb$ make phpstan
 332/332 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ------------------------------------------------------------------------------ 
  Line   module/Activity/src/Controller/AdminOptionController.php                      
 ------ ------------------------------------------------------------------------------ 
  92     Call to an undefined method Laminas\Form\ElementInterface::setCount().        
  102    Call to an undefined method Laminas\Form\ElementInterface::count().           
  103    Call to an undefined method Laminas\Form\ElementInterface::setCount().        
  114    Call to an undefined method Laminas\Form\ElementInterface::populateValues().  
  165    Call to an undefined method Laminas\Form\ElementInterface::setCount().        
  185    Call to an undefined method Laminas\Form\ElementInterface::setCount().        
 ------ ------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------- 
  Line   module/Activity/src/Form/Activity.php                                          
 ------ ------------------------------------------------------------------------------- 
  201    Call to an undefined method Laminas\Form\ElementInterface::getValueOptions().  
  206    Call to an undefined method Laminas\Form\ElementInterface::setValueOptions().  
  208    Call to an undefined method Laminas\Form\ElementInterface::getValueOptions().  
  213    Call to an undefined method Laminas\Form\ElementInterface::setValueOptions().  
  220    Call to an undefined method Laminas\Form\ElementInterface::setValueOptions().  
  282    Call to an undefined method Laminas\Form\ElementInterface::getFieldSets().     
 ------ ------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------- 
  Line   module/Activity/src/Service/Activity.php                                       
 ------ ------------------------------------------------------------------------------- 
  461    Call to an undefined method Doctrine\Common\Collections\Collection::unwrap().  
 ------ ------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------- 
  Line   module/Decision/src/Form/Notes.php                                             
 ------ ------------------------------------------------------------------------------- 
  80     Call to an undefined method Laminas\Form\ElementInterface::setValueOptions().  
 ------ ------------------------------------------------------------------------------- 

                                                                                                                    
 [ERROR] Found 14 errors                                                                                            
                                                                                                                    

make: *** [Makefile:80: phpstan] Fout 1

```

**Comment by tomudding** [comment]
> While I approve of the changes made in this PR, there's still some issues remaining.
> 
> ```
> koen@koen-HP-ZBook-Studio-G4-Kubuntu:~/gewisweb/gewisweb$ make phpstan
>  332/332 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
> 
> [removed for brevity]                                                                                                        
> 
> make: *** [Makefile:80: phpstan] Fout 1
> ```

Yes, I wanted to add those errors to the baseline, since there is no way to properly type the result of the function calling the unknown functions.

For `Collection::unwrap()` I am unsure what to do, perhaps you have a suggestion? We can add a union type for this specific instance, but ideally we would change it for all `Collections`, but a union type makes it look a bit messy.

**Comment by Koen1999** [comment]
> > While I approve of the changes made in this PR, there's still some issues remaining.
> > ```
> > koen@koen-HP-ZBook-Studio-G4-Kubuntu:~/gewisweb/gewisweb$ make phpstan
> >  332/332 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
> > 
> > [removed for brevity]                                                                                                        
> > 
> > make: *** [Makefile:80: phpstan] Fout 1
> > ```
> 
> Yes, I wanted to add those errors to the baseline, since there is no way to properly type the result of the function calling the unknown functions:
> 
> ```
> - '#Call to an undefined method Laminas\\Form\\ElementInterface\:\:(count|getFieldSets|getValueOptions|populateValues|setCount|setValueOptions)\(\).$#'
> ```
> 
> For `Collection::unwrap()` I am unsure what to do, perhaps you have a suggestion? We can add a union type for this specific instance, but ideally we would change it for all `Collections`, but a union type makes it look a bit messy.

Changing it to Collections seems most appropriate.

**Comment by Koen1999** [comment]
To get back to the collection issue. I see that the unwrap method is only implemented in the PersistentCollection class. I suggest checking whether the return type is an instance of this class before calling unwrap. I don't think this can be guaranteed for all return values of this method since the object is not always persisted.

**Comment by tomudding** [comment]
> To get back to the collection issue. I see that the unwrap method is only implemented in the PersistentCollection class. I suggest checking whether the return type is an instance of this class before calling unwrap. I don't think this can be guaranteed for all return values of this method since the object is not always persisted.

I think it is guaranteed that the `ActivityUpdateProposal`s in the collection are persisted. However, looking at it, we do not even need the `unwrap()`. We can directly call `first()`, which is also in the `Collection` interface. I'll change it in a bit (and test it).

**Comment by Koen1999** [comment]
> > To get back to the collection issue. I see that the unwrap method is only implemented in the PersistentCollection class. I suggest checking whether the return type is an instance of this class before calling unwrap. I don't think this can be guaranteed for all return values of this method since the object is not always persisted.
> 
> I think it is guaranteed that the `ActivityUpdateProposal`s in the collection are persisted. However, looking at it, we do not even need the `unwrap()`. We can directly call `first()`, which is also in the `Collection` interface. I'll change it in a bit (and test it).

Avoiding unwrap is even better!

**Pull request merged**
