### PR TITLE
Improved resource loading on frontpage

### PR DESCRIPTION
**Pull request by Koen1999**
This preloads all resources used on the front page by adding them to the head tag. This should increase page load time, especially on first visits. Rendering time is reduced. So nice enhancement :)

This PR was made to address concerns raised in #1352 .

### CODE REVIEW

**Review by tomudding — APPROVED** [review]
Looks good, I'll try to get a measurement before and after deploying this. That way we really know the impact of this change (specifically for first page load).

**Comment by tomudding** [comment]
Here is a before:

image

Most of the bytes downloaded are the result of jQuery. Timings are influenced mostly by the images (specifically the photo of the week, which should be scaled down a bit).

**Comment by tomudding** [comment]
And after:

image

Blocking time has indeed been reduced, but TTI is significantly more.

**Comment by Koen1999** [comment]
Perhaps this is a recommendation we can work on in a future PR:
Screenshot_20220206_131137

**Pull request merged**
