### PR TITLE
Revert "Add a missing >"

### PR DESCRIPTION
**Pull request by jszanto**
Reverts GEWIS/gewisweb#812

### CODE REVIEW

**Comment by BorBorBor** [comment]
@raketwissenschaftler thanks 4 assigning this to me, I have found the missing part: 

# >

**Comment by jszanto** [comment]
I suggest we create forks of Gecko, WebKit and Blink to support missing >. This would save us the effort of convincing W3C from implemting this in the specification.

**Comment by BorBorBor** [comment]
The old website did not have this problem, and editing it live via notepad on the GEWIS PCs did not yield this problem. I suggest rolling back the current version.

**Comment by raketwissenschaftler** [comment]
@BorBorBor I appreciate the suggestion, however, I think that important issues as this really need some more care. I would prefer if important issues such as these could be handled a bit more carefully and seriously in the future. Please also take into account what @jszanto said.

@Kevinjil: Can you please take a look at this issue?

**Comment by BorBorBor** [comment]
@kokx maybe we should consider asking Coppelmans to start drafting a proposal for a Senate Inequality.

**Comment by kokx** [comment]
@BorBorBor And of course, this has to be discussed at length at the Senaatsavond, before the Senate can make a decision about this important topic.

**Comment by raketwissenschaftler** [comment]
I have discussed the proposed changes with the board. They did not have a clear opinion about this, we will need to discuss it on the next GMM.

**Comment by BorBorBor** [comment]
I disagree about bothering the whole GMM with this. My preference would be to make this a key point in the long-term vision of GEWIS.

**Comment by kokx** [comment]
I agree that this needs to be part of long-term plans. However, I think this is much, much bigger than GEWIS. It should be obvious that this needs a judgement from the WISO.

**Comment by jszanto** [comment]
Closing this for now until we reach a consensus about this issue.

**Pull request closed without merging**
